language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
        
install:
- npm install

script: true

before_deploy:
- cat .netrc >> $HOME/.netrc
- chmod 0600 /home/travis/.netrc
- heroku apps
- heroku apps | grep -q mrr-$TRAVIS_BRANCH || heroku apps:create mrr-$TRAVIS_BRANCH
- heroku git:remote -a mrr-$TRAVIS_BRANCH

deploy:
  provider: heroku
  api_key: 53926d8b-cb90-4125-a242-afd000b84e61
  app: mrr-$TRAVIS_BRANCH
  on: $TRAVIS_BRANCH

after_deploy:
- ./node_modules/.bin/wdio wdio.conf || travis_terminate 1
